version: '3.7'
services:

  rabbitmq:
    restart: always
    image: rabbitmq:3.8
    env_file:
      - ./rabbitmq.env
    environment:
      # increase the timeout -- that a worker uses for working on the program and then sending an ack
      - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit consumer_timeout 172800000
    deploy:
      replicas: 1
      mode: replicated
    networks:
      - pipeline-net

  #creates the work messages
  producer:
    restart: always
    image: ghcr.io/anddann/upcy:1.6.2-SNAPSHOT
    depends_on:
      - rabbitmq
    deploy:
      # we only need one producer
      replicas: 1
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 90s
        window: 240s
    volumes:
      - ./upcyresults:/mnt/results
    env_file:
      - ./upcy.sample.env
    environment:
      - WORKER_NODE=false
    networks:
      - pipeline-net

  worker:
    restart: always
    image: ghcr.io/anddann/upcy:1.6.2-SNAPSHOT
    deploy:
      replicas: 2
      mode: replicated
      restart_policy:
        condition: on-failure
        delay: 30s
        window: 120s
    depends_on:
      - rabbitmq
      - producer
    volumes:
      - ./upcyresults:/mnt/results
    env_file:
      - ./upcy.sample.env
    environment:
      - WORKER_NODE=true
      - TIMEOUT=21600
    networks:
      - pipeline-net
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  pipeline-net:
    external: false